# Generated by Django 6.1.1 on 2026-09-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID do Tweet'),
        ),
    ]
